# Generated by Django 2.2.20 on 2021-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20210429_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=200)),
                ('from_currency_name', models.CharField(max_length=200)),
                ('to_currency_code', models.CharField(max_length=200)),
                ('to_currency_name', models.CharField(max_length=200)),
                ('exchange_rate', models.FloatField(default=0.0)),
                ('last_refreshed', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=200)),
                ('bid_price', models.FloatField(default=0.0)),
                ('ask_price', models.FloatField(default=0.0)),
            ],
        ),
    ]
